### ISSUE TITLE
Outdated description

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/Content#101]
Readme file for Content app contains some old, obsolete screens from Website app and steps that are no longer corrent. Readme file should be updated considering newest changes in website app.

**Comment by Mihaiii** [comment]
Are we talking about the readme.md from `develop` branch?

**Comment by Mihaiii** [comment]
I guess so. I'll have a look to see the latest steps needed in Website app.

**Comment by PatrykSzwer** [comment]
Yes, `develop` branch.

**Comment by Mihaiii** [comment]
Closing as done for Content 1.1.0.
