### ISSUE TITLE
Self.GET doesn't get the page from another app

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Content#104]
### Steps to reproduce
1. Run https://github.com/StarcounterApps/SignIn/commit/f4e3236811665c0cf0a1a38bb18f3bb97c983dfc (current latest version on develop)
2. Run https://github.com/StarcounterApps/Content/pull/102/commits/6093db13f9d65704b80dc56ba1b80fe7e8819ca6
3. Run https://github.com/StarcounterApps/Search/commit/231a07e17d42a4bc36c959bbbc65d81f99a85a81 (current latest version on develop)
4. Go to `http://localhost:8080/signin/signinuser` and log in (if you don't have a user, create an user using the button shown on that page)
5. Go to `http://localhost:8080/search/settings`, remove everything and then add `Simplified.Ring6.WebContent`.
6. Add some Content items: press "Create" on `http://localhost:8080/content/cms` write something at `Name` and then some text in the Visual editor.
7. Follow the steps shown in the gif:
![selfget](https://user-images.githubusercontent.com/8951553/30339661-a0558ffa-97a4-11e7-9f6e-c0ce42e55607.gif)

@alemoi You're the one I should ask in this case to have a look at it? :)

**Comment by Mihaiii** [comment]
@un-tone Could you please have a quick look on this issue? Don't waste any time reproducing it, I would just want to know if maybe I'd doing something wrong here.

Thanks in advance!

**Comment by un-tone** [comment]
OK

**Comment by un-tone** [comment]
I think a one app can't have a direct access to URIs of another one. You should use blending instead of it.

**Comment by Mihaiii** [comment]
Ok, thank you!
Closing.
