### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by joozek78** [StarcounterApps/Content#18]
1. Purpose
1. Quickstart
1. Details (if applicable)

**Comment by warpech** [comment]
@Mihaiii, as you have noticed, Content is quite an old initiative that we are resurrecting now. Once you learn how to get around, could you pls propose changes to `README.md` that explain the purpose of this app. What are the screens available in the app and how to use them? Pls refer to: https://github.com/StarcounterApps/Website

In future, when new functionality is added to the Content app, it needs to be described in README, too.

The essential feature is to explain how to use Content to present static and dynamic text in Website app. I can help with that if needed.

**Comment by Mackiovello** [comment]
Done with #49
