### ISSUE TITLE
Implement a preview feature

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#25]
For https://github.com/Starcounter/CompanyTrack/issues/316

To increase the user-friendliness, it should be possible to preview new content block before publishing. This is already implemented in the [markdown editor](https://github.com/Juicy/juicy-markdown-tabbededitor). Because of this, #24 should be solved first. 

The preview should work both for markup and markdown.

**Comment by Mihaiii** [comment]
Closing as done.
