### ISSUE TITLE
Make it possible to add links to pages on the relevant surface in the website app

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#28]
For https://github.com/Starcounter/CompanyTrack/issues/316

When creating or editing a page, there should be an option to add that page to the Launcher menu. This would make created pages more accessible.

**Comment by Mackiovello** [comment]
Since the Launcher is no longer in use, this issue is slightly changed. Instead of being able to add links to pages in the Launcher menu, it should be possible to blend all the available page links.

**Comment by Mihaiii** [comment]
^ @Mackiovello Can you please give me more details? I'm not really sure how the final result should look like. Can I start with the "Blending tutorial" or should I focus on something else for this issue?

**Comment by Mackiovello** [comment]
What I'm imagining is that it should be possible to place the links of pages wherever you want the same way that you can place content. 

For example, in the [README](https://github.com/StarcounterApps/Content/tree/develop), you're able to pin a content item with the text "This is an example!". Imagine if this content item contained a lot more info. Then it wouldn't make sense to show the whole thing, you'd rather just have a link to it. 

What I believe should be done is that with every new content page that is created, a corresponding link page should also be created automatically. The link can then be positioned the same way content is. 

Does that make sense?

**Comment by Mihaiii** [comment]
Ok, but just to clarify some things for myself:

> Then it wouldn't make sense to show the whole thing, you'd rather just have a link to it.

Isn't this the purpose of the Website app CRM, though (to show the whole content, not just a link page to the content) ? In what case would the user want to show a page with a link to the content page?

**Comment by Mihaiii** [comment]
In case you want a place in the Website app CRM in which all the available links to the content items to be displayed, I think this is an issue for the Webiste app since all are content items can be viewd at "/content/dynamic" + "Url" from Simplified.Ring6.WebContent .

**Comment by Mackiovello** [comment]
I think you have a good point. This was something I came up when we used the launcher and there was always a menu of links on the left side. It doesn't seem like this is actually needed now. Closing. 

If we feel like there's a need for it later, we can reopen.
