### ISSUE TITLE
Root partials views does not use shadow dom layouts

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Content#39]
### Steps to reproduce
@Mackiovello please correct me if I'm wrong
1. Create a partial that is returned as a root one (that uses `PartialToStandaloneHTMLProvider`), like https://github.com/StarcounterApps/Content/blob/905a684161ab71aea94bf43103f3f33bdd024a58/src/Content/Api/PartialHandlers.cs#L34
2. Open it in browsers

### Expected result
declarative shadow DOM should be applied

### Actual result
declarative shadow DOM is not applied

##### Involved apps' version

https://github.com/StarcounterApps/Content/blob/905a684161ab71aea94bf43103f3f33bdd024a58
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Screenshot

@Mackiovello  could you provide one?

### Investigation

It happens because on default `PartialToStandaloneHTMLProvider` middleware, we are using `<template is="imported-template">` instead of `<starcounter-include>`, so the element which does not have any  layout capabilities.

#### Related issues
https://github.com/Starcounter/starcounter-include/issues/29

**Comment by Mackiovello** [comment]
This seems right. 

Steps to reproduce:
1. Start SignIn and Content (https://github.com/StarcounterApps/SignIn/commit/224070465b64212ac96fbce0f0a62e3e5eb90d84 and https://github.com/StarcounterApps/Content/commit/83007587cf14a031780a386686450cb479a631ef)
2. Sign in
3. Go to `http://localhost:8080/content/partials/create-item`

Screenshot:
![shot](https://cloud.githubusercontent.com/assets/19392292/25222443/c1c7fadc-25b8-11e7-9172-3ff64d475e90.PNG)

Starcounter version: 2.3.0.6278

**Comment by tomalec** [comment]
I have created an issue in Starcounter https://github.com/Starcounter/Home/issues/89

**Comment by tomalec** [comment]
Fixed by https://github.com/Starcounter/level1/pull/4223
