### ISSUE TITLE
Content needs an icon that is displayed in Launchpad

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Content#46]
Unlike other apps (People, Images, Products), Content does not present at icon in the Launchpad.

The icon should point to `/content`.

Please choose an icon from https://thenounproject.com/ (we have a license) and add it to the Content app.

**Comment by warpech** [comment]
Assigning this as the first task to @Mihaiii.

@Mackiovello could you pls help @Mihaiii regarding the initial setup as well as guide him trough the app authoring [Guidelines](https://starcounter.gitbooks.io/guidelines/content/)?

**Comment by Mackiovello** [comment]
Fixed with #48, closing
