### ISSUE TITLE
WYSIWYG editor

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Content#52]
There are different options for this: 
1. [wysiwg-e](https://github.com/miztroh/wysiwyg-e) - there are some problems relating to images (more details in PR #53 ). If there's just text, everything is fine.
2. [polymer-tinymce](https://github.com/JaySunSyn/polymer-tinymce) - tried to integrate it; doesn't work or I'm doing something wrong.
3. [quill](https://github.com/quilljs/quill) - I will try to integrate it.
4. ... ?

**Comment by Mihaiii** [comment]
For the moment I gave up on the idea of making an element that wraps ace-editor and a wysiwyg editor; instead I just replaced the ace-editor wrapper with the tinymce wrapper that @alshakero used in another project (thanks again!).

**Comment by Mackiovello** [comment]
Are we going to use TinyMCE or WYSIWYG-e? Please close the other PR to avoid confusion

**Comment by alshakero** [comment]
If there is still room for an opinion I strongly advise against WYSIWYG-e; it destroys the performance.

**Comment by Mihaiii** [comment]
Closed both PR. Please don't delete the branches yet.
Will go TinyMCE but, again, it would great if someone would try to reproduce #issuecomment-309714438 .

**Comment by Mihaiii** [comment]
@habib535 Could you please help me with the above test (previous comment).
Shouldn't take more than 5 minutes.

I guess you could use `git checkout 2e4801567ab4fa1f4cc5fb6d51f2e8d101e92a27` .

**Comment by habib535** [comment]
I tried running the above test with `tinymce` branch and it worked for me without any errors!

**Comment by Mihaiii** [comment]
^ Thanks!

**Comment by Mihaiii** [comment]
Closing as done.
