### ISSUE TITLE
Page doesn't refresh at sign in/sign out

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Content#55]

**Comment by Mackiovello** [comment]
This can be fixed with commit hooks, for example: https://github.com/StarcounterApps/Chatter/blob/a721ca7979244cec102ca1874e6d2a1592067589/src/Chatter/Api/CommitHooks.cs

**Comment by Mihaiii** [comment]
It has them. The problem is that the page that it is suppose to refresh comes as null. Probably something related to "Session.Current.Data". I'm looking more in depth into it atm.

**Comment by Mihaiii** [comment]
I had a "Page not found" in the top bar (probably was trying to access some Pin URI that isn't defined). The design was also similar to the default template from Website and not the one from SampleWebsiteTheme (nothing changed after running SampleWebsiteTheme). 

After I deleted the db and rerun Website and SampleWebsiteTheme, the "Page not found" disappeared and now it also refreshes at sign in / sign out.

Don't know if I should close the issue or change something.

**Comment by Mackiovello** [comment]
I can't recreate it with Launcher and SignIn. Closing as no longer relevant. The problem is probably in Website

**Comment by Mihaiii** [comment]
Had a look in the history because I wanted to erase something and saw this comment:
https://github.com/StarcounterApps/Content/commit/a493766da7b6ea2f96159b4ae27d1ac70b90f21e#diff-ccd4cf3920c56e95dcc937e7fa590631L34

Was this discussed anywhere on github? 
Erasing that line solves this issue so I'd like to know if there could occur any problems if I erase it.
From my tests everything seems to work as expected.

**Comment by Mihaiii** [comment]
Closing as fixed.
