### ISSUE TITLE
Clicking view on an empty item throws an exception

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#57]
![exceptionnew](https://user-images.githubusercontent.com/19392292/27329525-2e1a163e-55b6-11e7-829b-82e6172d6d1b.gif)
 ```
Error 404: Resource "/content/dynamicnull" not found.
```

**Comment by Mackiovello** [comment]
Related to #56

**Comment by Mihaiii** [comment]
Closing as fixed.
