### ISSUE TITLE
Change icons to SVG

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#58]
In these two pages, a PNG and glyphicon is used. These should be replaced with SVGs: https://github.com/StarcounterApps/Content/blob/develop/src/Content/wwwroot/Content/views/AppIcon.html
https://github.com/StarcounterApps/Content/blob/develop/src/Content/wwwroot/Content/views/LauncherMenu.html

**Comment by Mihaiii** [comment]
Just to clarify some things for myself: 
Do we even use the "menu" blending point anymore? What would happen if I delete from Content everything that's related to it?

**Comment by Mackiovello** [comment]
Not really. But almost all of the sample apps use it: https://github.com/search?utf8=%E2%9C%93&q=org%3AStarcounterApps++Blender.MapUri+%22menu%22&type=Code

I'm not sure how this works with the Website app. Check with @bouguila 

If it's not used anymore, then it should be removed

**Comment by warpech** [comment]
Also, the icon which is a PNG looks like a Calendar to me: https://github.com/StarcounterApps/Content/blob/fea1e8e0b0f1cb0587c7955325b213c6f456178a/src/Content/wwwroot/Content/images/content.png

The icon for Content app should look more like:

- https://thenounproject.com/term/text-editor/532870/
- https://thenounproject.com/term/initial/75970/
- https://thenounproject.com/term/compose/1084354/

**Comment by warpech** [comment]
> I'm not sure how this works with the Website app. Check with @bouguila
> If it's not used anymore, then it should be removed

`menu` was heavily used in Launcher, now it is **temporarily** not used. See: https://github.com/Starcounter/RebelsLounge/issues/53

I agree that `menu` Page can be removed for now.

**Comment by Mihaiii** [comment]
Yes, already replaced it (didn't push yet). That was my first task and I choose a random icon.
Thanks, will remove it.

**Comment by Mihaiii** [comment]
Closing as done.
