### ISSUE TITLE
Create automatically generated table of contents

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#64]
When creating a new piece of content, it should be added to an automatically generated table of contents.

I'm imagining something like this:

```cs
Handle.GET("/content/partials/table-of-content", () => 
{
    // Gets all the content items that has been marked as "show in table in contents" 
    // sets them as the data object of a view-model
    // returns the view-model
}
```

```json
{
    "html": "/your/path.html",
    "content": [ { } ]
}
```

```html
<template>
  <template is="dom-repeat">
    <div class="content-item">{{model.content}}</div>
  </template>
</template>
```

So there can be set point in the website app where the table of contents is displayed. When a new item is created, it's also added if the user doesn't explicitly ask to exclude it.

Please ask if you need a clarification.

**Comment by Mihaiii** [comment]
1. I don't think I can add a new db column in Simplified.Ring6.WebContent from Content app .
2. Didn't really knew what style to apply tot he page. This pretty much depends of what the user wants. Kept it as simple as possible for the moment.

**Comment by Mihaiii** [comment]
Closing as done.
