### ISSUE TITLE
Firefox: "Assertion failed" error

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Content#79]
### Steps to reproduce
Go to `http://localhost:8080/content/cms/` in **Firefox** and create new item.

Write something in the `Visual` tab. Press enter. Write something on the new line.

In console you will see:

> Error: Assertion failed  webcomponents.min.js:11:1561
> 	n http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:1561
> 	t http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:22587
> 	removeChild http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:26710
> 	x/</</e.prototype[t] http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:4487
> 	remove http://localhost:8080/sys/to-markdown/dist/to-markdown.js:740:3
> 	collapseWhitespace http://localhost:8080/sys/to-markdown/dist/to-markdown.js:692:16
> 	htmlToDom http://localhost:8080/sys/to-markdown/dist/to-markdown.js:46:3
> 	toMarkdown http://localhost:8080/sys/to-markdown/dist/to-markdown.js:206:15
> 	htmlValueChanged http://localhost:8080/Content/elements/content-tabbededitor/content-tabbededitor.html.js:61:38
> 	_observerEffect http://localhost:8080/sys/polymer/polymer.html.js:1587:1
> 	_effectEffects http://localhost:8080/sys/polymer/polymer.html.js:1432:1
> 	_propertySetter http://localhost:8080/sys/polymer/polymer.html.js:1416:1
> 	__setProperty http://localhost:8080/sys/polymer/polymer.html.js:1425:1
> 	_applyEffectValue http://localhost:8080/sys/polymer/polymer.html.js:1908:1
> 	_annotationEffect http://localhost:8080/sys/polymer/polymer.html.js:1571:1
> 	_annotationPathEffect http://localhost:8080/sys/polymer/polymer.html.js:2198:1
> 	_pathEffector http://localhost:8080/sys/polymer/polymer.html.js:2188:1
> 	_notifyPath http://localhost:8080/sys/polymer/polymer.html.js:2089:1
> 	set http://localhost:8080/sys/polymer/polymer.html.js:2148:1
> 	_notedListenerFactory/< http://localhost:8080/sys/polymer/polymer.html.js:1541:1
> 	_notifyListener http://localhost:8080/sys/polymer/polymer.html.js:2057:8
> 	_addNotifyListener/< http://localhost:8080/sys/polymer/polymer.html.js:1559:8
> 	g http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:14804
> 	w http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:14150
> 	f http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:13890
> 	p http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:13402
> 	dispatchEvent http://localhost:8080/sys/webcomponentsjs/webcomponents.min.js:11:20265
> 	fire http://localhost:8080/sys/polymer/polymer.html.js:1268:1
> 	_notifyChange http://localhost:8080/sys/polymer/polymer.html.js:1399:1
> 	_notifyEffect http://localhost:8080/sys/polymer/polymer.html.js:1578:1
> 	_effectEffects http://localhost:8080/sys/polymer/polymer.html.js:1432:1
> 	_propertySetter http://localhost:8080/sys/polymer/polymer.html.js:1416:1
> 	setter http://localhost:8080/sys/polymer/polymer.html.js:1495:1
> 	save http://localhost:8080/Content/elements/content-wrapped-tinymce/content-wrapped-tinymce.html.js:29:33
> 	bound save self-hosted:913:17
> 	e http://localhost:8080/sys/tinymce/tinymce.min.js:10:2562
> 	fire http://localhost:8080/sys/tinymce/tinymce.min.js:10:4074
> 	add http://localhost:8080/sys/tinymce/tinymce.min.js:8:17938
> 	f http://localhost:8080/sys/tinymce/tinymce.min.js:12:17765
> 	s/< http://localhost:8080/sys/tinymce/tinymce.min.js:12:17950
> 	e http://localhost:8080/sys/tinymce/tinymce.min.js:10:2562
> 	fire http://localhost:8080/sys/tinymce/tinymce.min.js:10:4074
> 	h http://localhost:8080/sys/tinymce/tinymce.min.js:11:20049
> 	a http://localhost:8080/sys/tinymce/tinymce.min.js:2:8288
> 	p http://localhost:8080/sys/tinymce/tinymce.min.js:2:8635

**Comment by Mihaiii** [comment]
Can't solve this at this moment.
An update of webcomponents.js might just do it.

**Comment by warpech** [comment]
Did you try Firefox debugging tools? Some value might be lost in one of our functions, not in `webcomponents.js` or Polymer. Did you do some investigation what might be the root of the problem in the above stack trace?

Does it work ok in Edge?

@tomalec can you pls help?

**Comment by warpech** [comment]
Try to insert an unminified version of `webcomponents.js` at the path of `/sys/webcomponents.min.js`. This will make it easier to understand what this script is expecting and what it is getting.

**Comment by Mihaiii** [comment]
> Did you try Firefox debugging tools? Some value might be lost in one of our functions, not in webcomponents.js or Polymer. Did you do some investigation what might be the root of the problem in the above stack trace?
> 
> Does it work ok in Edge?

The child that should be removed is not wrapped.
I put an breakpoint here: https://github.com/Starcounter/level1/blob/a6b632342b6f1e8dce3db98ef1ebd1a9eb6406ec/src/BuildSystem/ClientFiles/StaticFiles/sys/document-register-element/examples/bower_components/webcomponentsjs/webcomponents.js#L1830 .

If I write in console `childWrapper = wrap(childWrapper);` no error is thrown.
There are more issue that I think are related to this "not wrapped" problem.

Also doesn't work in Edge.

**Comment by Mihaiii** [comment]
@alshakero Can you please have a quick look at this problem? Have you encountered it before?

**Comment by alshakero** [comment]
Will see

**Comment by alshakero** [comment]
I'm getting this, how do I auth 
![image](https://user-images.githubusercontent.com/17054134/28567244-fcf8aec0-7131-11e7-9043-b9cef3861876.png)

**Comment by Mihaiii** [comment]
Thank you!

For auth:
1. Get [SignIn app](https://github.com/StarcounterApps/SignIn)
2. Go to `http://localhost:8080/signin/generateadminuser`
3. Go to `http://localhost:8080/signin/profile` and auth with user "admin", pass "admin"
4. Retry `http://localhost:8080/content/cms`

In the TinyMCE custom element you made some workaround for the fact that `this.MCEInstance.getContent()` doesn't work in Firefox. I think at its core, it's the same problem as the one presented here.

**Comment by alshakero** [comment]
What is your SC version?

**Comment by alshakero** [comment]
### Pin pointed it

`toMarkdown` has a bug with Firefox. It breaks on newlines (`\n`).

Change [this line](https://github.com/StarcounterApps/Content/blob/develop/src/Content/wwwroot/Content/elements/content-tabbededitor/content-tabbededitor.html#L207) to:
```js
const htmlValue = newValue.replace(/\n/g, '');
this.markdownValue = toMarkdown(htmlValue, { converters: [{ filter: ['em', 'i'], replacement: (c) => ('*'+c+'*') }] });
```
And it will work perfectly. I suggest you prepare a jsfiddle and report an issue to https://github.com/domchristie/to-markdown/.

**Comment by Mihaiii** [comment]
This actually works and there don't seem to be any unwanted side effects :).
I feel like I missed my shot with this one. :)))
Thank you!

**Comment by alshakero** [comment]
It would cause some trouble in `<pre>` and `<textarea>` tags; they depend on new lines. But I'm bit sure if TinyMCE produces those tags.

**Comment by Mihaiii** [comment]
It might cause problems when the user uses the HTML editor, as `newVlaue` (is not constant) updates after every character inserted. Made some changes, we'll see.

**Comment by alshakero** [comment]
Anytime!

**Comment by Mihaiii** [comment]
Closing as I merged the PR with the fix.
