### ISSUE TITLE
CMS layout is broken in Firefox

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#86]
Firefox:
![capture](https://user-images.githubusercontent.com/19392292/28511893-add319a8-704f-11e7-91b6-7030bd919d40.PNG)

Compare to Chrome:

![capture](https://user-images.githubusercontent.com/19392292/28511910-c0ab6f58-704f-11e7-83fb-68d0aaa2501b.PNG)

**Comment by Mihaiii** [comment]
Closing as done.
